/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package time_table_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import time_table_management_system.TableStudentGroups;

/**
 *
 * @author NISHADI
 */
public class ManageStudentsGroups extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentsGroups
     */
    public ManageStudentsGroups() {
        initComponents();
       
    }
    
       public Connection getConnection(){
      Connection con;
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmnew","root","");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
        
    }
       
           public ArrayList<Students> getStudentsList()
    {
        ArrayList<Students> studentsList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `student`";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Students students;
            while(rs.next()){
                students= new Students(rs.getInt("sId"),rs.getString("sYear"),rs.getString("sSemester"),rs.getString("sProgramme"),rs.getString("sMaiGroupNumber"),rs.getString("sSubGroupNumber"),rs.getString("sMainGroupId"),rs.getString("sSubGroupId"));
                studentsList.add(students);
                
            }
               
        }catch(Exception e){
            e.printStackTrace();
        }
        return studentsList;
    } 
       
           

                       //display data in jTable
  /* public void Show_StudentTable_In_JTable(){
        ArrayList<Students> list = getStudentsList();
       // DefaultTableModel model =(DefaultTableModel).studentTable.getModel();
      // DefaultTableModel model = .studentTable.getModel();
        Object[] row = new Object[8];
        for(int i = 0; i < list.size(); i++)
        {
            
            row[0] = list.get(i).getSID();
            row[1] = list.get(i).getYear();
            row[2] = list.get(i).getSemester();
            row[3] = list.get(i).getProgramme();
            row[4] = list.get(i).getMainGroupNumber();
            row[5] = list.get(i).getSubGroupNumber();
            row[6] = list.get(i).getMainGroupId();
            row[7] = list.get(i).getSubGroupId();
            
            
           //model.addRow(row);
            
            
        }
    }*/
                //Exequte The Sql Query
   public void executeSQlQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                //DefaultTableModel model =(DefaultTableModel).studentTable.getModel();
                  //model.setRowCount(0);
                 // Show_StudentTable_In_JTable();
                          
                JOptionPane.showMessageDialog(null, "Data"+message+" Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not"+message);
            }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ManProgramme = new javax.swing.JTextField();
        ManMainGroupNumber = new javax.swing.JTextField();
        ManSubGroupNumber = new javax.swing.JTextField();
        GroupID = new javax.swing.JTextField();
        subGroupID = new javax.swing.JTextField();
        ManUpdate = new javax.swing.JButton();
        ManDelete = new javax.swing.JButton();
        ManClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ManID = new javax.swing.JTextField();
        ManViewTable = new javax.swing.JButton();
        manYear = new javax.swing.JComboBox<>();
        manSemeseter = new javax.swing.JComboBox<>();
        jButtonGenerateID = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Academic Year");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Acadamic Semester");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Programme");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Main Group Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sub Group Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Main Group ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sub Group ID");

        GroupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupIDActionPerformed(evt);
            }
        });

        ManUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManUpdate.setText("Update");
        ManUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManUpdateActionPerformed(evt);
            }
        });

        ManDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManDelete.setText("Delete");
        ManDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManDeleteActionPerformed(evt);
            }
        });

        ManClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManClear.setText("Clear");
        ManClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManClearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("ID");

        ManViewTable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManViewTable.setText("View Table");
        ManViewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManViewTableActionPerformed(evt);
            }
        });

        manYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y1", "Y2", "Y3", "Y4", " " }));

        manSemeseter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2" }));

        jButtonGenerateID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonGenerateID.setText("Generate IDs");
        jButtonGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManSubGroupNumber)
                            .addComponent(GroupID)
                            .addComponent(subGroupID)
                            .addComponent(ManMainGroupNumber)
                            .addComponent(ManProgramme)
                            .addComponent(ManID)
                            .addComponent(manYear, 0, 122, Short.MAX_VALUE)
                            .addComponent(manSemeseter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonGenerateID)
                        .addGap(28, 28, 28)
                        .addComponent(ManUpdate)
                        .addGap(29, 29, 29)
                        .addComponent(ManDelete)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ManViewTable)
                .addGap(64, 64, 64)
                .addComponent(ManClear)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ManID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manSemeseter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ManProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ManMainGroupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ManSubGroupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(GroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(subGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerateID)
                    .addComponent(ManUpdate)
                    .addComponent(ManDelete))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManViewTable)
                    .addComponent(ManClear))
                .addGap(33, 33, 33))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Student Groups Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManUpdateActionPerformed
        // TODO add your handling code here:
        String id = ManID.getText();
        String year = (String) manYear.getSelectedItem();
        String semester = (String) manSemeseter.getSelectedItem();
        String programme = ManProgramme.getText();
        String mainGroupNumber = ManMainGroupNumber.getText();
        String subGroupNumber = ManSubGroupNumber.getText();
        String mainGroupId = GroupID.getText();
        String subGroupId = subGroupID.getText();
        
        try{
            
                String query = "UPDATE `student` SET `sYear`='"+manYear.getSelectedItem()+"',`sSemester`='"+manSemeseter.getSelectedItem()+"',`sProgramme`='"+ManProgramme.getText()+"',`sMaiGroupNumber`='"+ManMainGroupNumber.getText()+"',`sSubGroupNumber`='"+ManSubGroupNumber.getText()+"',`sMainGroupId`='"+GroupID.getText()+"',`sSubGroupId`='"+subGroupID.getText()+"' WHERE `sID`="+ManID.getText();
                  Connection con = getConnection();      
               //PreparedStatement pst = con.preparedStatement(query);
               //pst.execute();
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
       String query = "UPDATE `student` SET `sYear`='"+manYear.getSelectedItem()+"',`sSemester`='"+manSemeseter.getSelectedItem()+"',`sProgramme`='"+ManProgramme.getText()+"',`sMaiGroupNumber`='"+ManMainGroupNumber.getText()+"',`sSubGroupNumber`='"+ManSubGroupNumber.getText()+"',`sMainGroupId`='"+GroupID.getText()+"',`sSubGroupId`='"+subGroupID.getText()+"' WHERE `sID`="+ManID.getText();
         //String query ="UPDATE `moduletag` SET `name`='"+T2_ModuleName.getText()+"',`code`='"+T2_moduleCode.getText()+"',`type01`='"+T2_AddT01.getText()+"',`type01Code`='"+T2_T01Code.getText()+"',`type02`='"+T2_AddT2.getText()+"',`type02Code`='"+T2_T2Code.getText()+"',`type03`='"+T2_AddT3.getText()+"',`type03Code`='"+T2_T3Code.getText()+"' WHERE `indexId`="+T2Id.getText();
        executeSQlQuery(query, " Updated");
    }//GEN-LAST:event_ManUpdateActionPerformed

    private void ManDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManDeleteActionPerformed
        // TODO add your handling code here:
        String query ="DELETE FROM `student` WHERE `sID` = "+ManID.getText();
        executeSQlQuery(query, " Deleted");
        
        
        TableStudentGroups.AddRowToJTable(new Object[]{
                                                         ManID.getText(),
                                                         manYear.getSelectedItem(),
                                                         manSemeseter.getSelectedItem(),
                                                         ManProgramme.getText(),
                                                         ManMainGroupNumber.getText(),
                                                         ManSubGroupNumber.getText(),
                                                         GroupID.getText(),
                                                         subGroupID.getText(),
                               });
      
    }//GEN-LAST:event_ManDeleteActionPerformed

    private void ManViewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManViewTableActionPerformed
        // TODO add your handling code here:
         TableStudentGroups studentTable = new TableStudentGroups();
        studentTable.setVisible(true);
        this.dispose();
        
        
        TableStudentGroups.AddRowToJTable(new Object[]{
                                                         ManID.getText(),
                                                         manYear.getSelectedItem(),
                                                         manSemeseter.getSelectedItem(),
                                                         ManProgramme.getText(),
                                                         ManMainGroupNumber.getText(),
                                                         ManSubGroupNumber.getText(),
                                                         GroupID.getText(),
                                                         subGroupID.getText(),
                               });
    }//GEN-LAST:event_ManViewTableActionPerformed

    private void GroupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupIDActionPerformed

    private void manYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manYearActionPerformed

    private void ManClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManClearActionPerformed
        // TODO add your handling code here:
        ManID.setText(null);
        ManProgramme.setText(null);
        ManMainGroupNumber.setText(null);
        ManSubGroupNumber.setText(null);
        GroupID.setText(null);
        subGroupID.setText(null);
    }//GEN-LAST:event_ManClearActionPerformed

    private void jButtonGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateIDActionPerformed
        // TODO add your handling code here:
        String year = (String) manYear.getSelectedItem();
        String semester = (String) manSemeseter.getSelectedItem();
        String programme = ManProgramme.getText();
        String mainGroupNumber = ManMainGroupNumber.getText();
        String subGroupNumber = ManSubGroupNumber.getText();
        
        
        String mainGroupId = (((year +semester)+"."+programme)+"."+mainGroupNumber);
        GroupID.setText(""+mainGroupId);
        
        String subGroupId = ((((year +semester)+"."+programme)+"."+mainGroupNumber)+"."+subGroupNumber);
        subGroupID.setText(""+subGroupId);
    }//GEN-LAST:event_jButtonGenerateIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentsGroups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField GroupID;
    private javax.swing.JButton ManClear;
    private javax.swing.JButton ManDelete;
    public javax.swing.JTextField ManID;
    public javax.swing.JTextField ManMainGroupNumber;
    public javax.swing.JTextField ManProgramme;
    public javax.swing.JTextField ManSubGroupNumber;
    private javax.swing.JButton ManUpdate;
    private javax.swing.JButton ManViewTable;
    private javax.swing.JButton jButtonGenerateID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> manSemeseter;
    public javax.swing.JComboBox<String> manYear;
    public javax.swing.JTextField subGroupID;
    // End of variables declaration//GEN-END:variables

    private void setRowCount(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
