/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package time_table_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author NISHADI
 */
public class Overlapping extends javax.swing.JFrame {

    /**
     * Creates new form Overlapping
     */
    public Overlapping() {
        initComponents();
    }

    public Connection getConnection(){
      Connection con;
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmnew","root","");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
        
    }
    
          
    
    public ArrayList<Overlapes> getOverlapesList()
    {
        ArrayList<Overlapes> overlapesList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `overlape`";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Overlapes overlapes;
            while(rs.next()){
               // overlapes = new Overlapes(rs.getString("overYear"),rs.getString("over_Semester"),rs.getString("overSpecial"),rs.getString("overTag"),rs.getString("overCode1"),rs.getString("overCode2"),rs.getString("overCode3"),rs.getString("overCode4"));
               // overlapesList.add(overlapes);
                
                 overlapes = new Overlapes(rs.getInt("overID"),rs.getString("overYear"),rs.getString("over_Semester"),rs.getString("overSpecial"),rs.getString("overTag"),rs.getString("overCode1"),rs.getString("overCode2"),rs.getString("overCode3"),rs.getString("parCode4"),rs.getString("overSe1"),rs.getString("overSe2"),rs.getString("overSe3"),rs.getString("overSe4"));
                 overlapesList.add(overlapes);
                
                
            }
               
        }catch(Exception e){
            e.printStackTrace();
        }
        return overlapesList;
    }
           
             
    //Exequte The Sql Query
   public void executeSQlQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
               
                JOptionPane.showMessageDialog(null, "Data"+message+" Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not"+message);
            }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_OverlappingGetData = new javax.swing.JButton();
        jButton_OverlappingView = new javax.swing.JButton();
        jComboBox_AcademicYear = new javax.swing.JComboBox<>();
        jComboBox_GID1 = new javax.swing.JComboBox<>();
        jComboBox_GID2 = new javax.swing.JComboBox<>();
        jComboBox_GID3 = new javax.swing.JComboBox<>();
        jComboBox_GID4 = new javax.swing.JComboBox<>();
        jButton_OverlappingAdd1 = new javax.swing.JButton();
        jComboBox_AcademicSemester = new javax.swing.JComboBox<>();
        jComboBox_Special = new javax.swing.JComboBox<>();
        jComboBox_Tag = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_Se1 = new javax.swing.JComboBox<>();
        jComboBox_Se2 = new javax.swing.JComboBox<>();
        jComboBox_Se3 = new javax.swing.JComboBox<>();
        jComboBox_Se4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton_ovBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 62, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Non Overlapping Sessions");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Academic Year:-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Group ID:-");

        jButton_OverlappingGetData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_OverlappingGetData.setText("Get Data");
        jButton_OverlappingGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OverlappingGetDataActionPerformed(evt);
            }
        });

        jButton_OverlappingView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_OverlappingView.setText("View Table");
        jButton_OverlappingView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OverlappingViewActionPerformed(evt);
            }
        });

        jComboBox_AcademicYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_GID1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_GID2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_GID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_GID2ActionPerformed(evt);
            }
        });

        jComboBox_GID3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_GID4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_OverlappingAdd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_OverlappingAdd1.setText("Add");
        jButton_OverlappingAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OverlappingAdd1ActionPerformed(evt);
            }
        });

        jComboBox_AcademicSemester.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Special.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Tag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Academic Semester:-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Specalization:-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tag:-");

        jComboBox_Se1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Se2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Se3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Se4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Session:-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_GID1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_GID2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_GID3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_GID4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_Tag, 0, 145, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Special, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_AcademicSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_AcademicYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(127, 127, 127))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_OverlappingGetData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButton_OverlappingAdd1)
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_Se1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_Se2, 0, 109, Short.MAX_VALUE)
                                .addComponent(jComboBox_Se3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_Se4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton_OverlappingView, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(101, 101, 101))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_AcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_AcademicSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Special, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Se1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Se2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jComboBox_Se3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Se4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_GID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox_GID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox_GID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_GID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OverlappingView)
                    .addComponent(jButton_OverlappingAdd1)
                    .addComponent(jButton_OverlappingGetData))
                .addGap(31, 31, 31))
        );

        jButton_ovBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_ovBack.setText("Back");
        jButton_ovBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ovBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton_ovBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton_ovBack)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OverlappingGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OverlappingGetDataActionPerformed
        // TODO add your handling code here:
        
         try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sYear FROM `student`");
            
            
            while(rs.next()){
                String pYe = rs.getString("sYear");
                jComboBox_AcademicYear.addItem(pYe);
                
            }
           
            
        }catch(SQLException e){
            
        } 
        
        
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sSemester FROM `student`");
            
            
            while(rs.next()){
                String pSem = rs.getString("sSemester");
                jComboBox_AcademicSemester.addItem(pSem);
                
            }
           
            
        }catch(Exception e){
            
        } 
        
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sProgramme FROM `student`");
            
            
            while(rs.next()){
                String pProgramme = rs.getString("sProgramme");
                jComboBox_Special.addItem(pProgramme);
                
            }
           
            
        }catch(Exception e){
            
        } 
        
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct moType FROM `tags`");
            
            
            while(rs.next()){
                String pTag = rs.getString("moType");
                jComboBox_Tag.addItem(pTag);
                
            }
           
            
        }catch(Exception e){
            
        } 
        
         try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sub_code FROM `session`");
            
           while(rs.next()){
                String pCode1 = rs.getString("sub_code");
                jComboBox_GID1.addItem(pCode1);
                jComboBox_GID2.addItem(pCode1);
                jComboBox_GID3.addItem(pCode1);
                jComboBox_GID4.addItem(pCode1);
            }
            
        }catch(Exception e){
            
        } 
      
         
    try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct session_ID FROM `session`");
            
           while(rs.next()){
                String sess = rs.getString("session_ID");
                jComboBox_Se1.addItem(sess);
                jComboBox_Se2.addItem(sess);
                jComboBox_Se3.addItem(sess);
                jComboBox_Se4.addItem(sess);
            }
            
        }catch(Exception e){
            
        }
          
    }//GEN-LAST:event_jButton_OverlappingGetDataActionPerformed

    private void jButton_ovBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ovBackActionPerformed
        // TODO add your handling code here:
        SessionT sess = new SessionT();
        sess.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ovBackActionPerformed

    private void jComboBox_GID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_GID2ActionPerformed

    private void jButton_OverlappingAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OverlappingAdd1ActionPerformed
        // TODO add your handling code here:
      
     //String query = "INSERT INTO `overlape`(`overYear`, `over_Semester`, `overSpecial`, `overTag`, `overCode1`, `overCode2`, `overCode3`, `overCode4`, `overSe1`, `overSe2`, `overSe3, `overSe4`) VALUES ('"+jComboBox_AcademicYear.getSelectedItem()+"','"+jComboBox_AcademicSemester.getSelectedItem()+"','"+jComboBox_Special.getSelectedItem()+"','"+jComboBox_Tag.getSelectedItem()+"','"+jComboBox_Code1.getSelectedItem()+"','"+jComboBox_Code2.getSelectedItem()+"','"+jComboBox_Code3.getSelectedItem()+"','"+jComboBox_Code4.getSelectedItem()+"','"+jComboBox_Se1.getSelectedItem()+"','"+jComboBox_Se2.getSelectedItem()+"','"+jComboBox_Se3.getSelectedItem()+"','"+jComboBox_Se4.getSelectedItem()+"')";
     String query = "INSERT INTO `overlape`(`overYear`, `over_Semester`, `overSpecial`, `overTag`, `overCode1`, `overCode2`, `overCode3`, `overCode4`, `overSe1`, `overSe2`, `overSe3`, `overSe4`) VALUES ('"+jComboBox_AcademicYear.getSelectedItem()+"','"+jComboBox_AcademicSemester.getSelectedItem()+"','"+jComboBox_Special.getSelectedItem()+"','"+jComboBox_Tag.getSelectedItem()+"','"+jComboBox_GID1.getSelectedItem()+"','"+jComboBox_GID2.getSelectedItem()+"','"+jComboBox_GID3.getSelectedItem()+"','"+jComboBox_GID4.getSelectedItem()+"','"+jComboBox_Se1.getSelectedItem()+"','"+jComboBox_Se2.getSelectedItem()+"','"+jComboBox_Se3.getSelectedItem()+"','"+jComboBox_Se4.getSelectedItem()+"')";
     executeSQlQuery(query, " Inserted");
              
    }//GEN-LAST:event_jButton_OverlappingAdd1ActionPerformed

    private void jButton_OverlappingViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OverlappingViewActionPerformed

        // TODO add your handling code here:
        OverlapTable ove = new OverlapTable();
        ove.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_OverlappingViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Overlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Overlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Overlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Overlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Overlapping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_OverlappingAdd1;
    private javax.swing.JButton jButton_OverlappingGetData;
    private javax.swing.JButton jButton_OverlappingView;
    private javax.swing.JButton jButton_ovBack;
    private javax.swing.JComboBox<String> jComboBox_AcademicSemester;
    private javax.swing.JComboBox<String> jComboBox_AcademicYear;
    private javax.swing.JComboBox<String> jComboBox_GID1;
    private javax.swing.JComboBox<String> jComboBox_GID2;
    private javax.swing.JComboBox<String> jComboBox_GID3;
    private javax.swing.JComboBox<String> jComboBox_GID4;
    private javax.swing.JComboBox<String> jComboBox_Se1;
    private javax.swing.JComboBox<String> jComboBox_Se2;
    private javax.swing.JComboBox<String> jComboBox_Se3;
    private javax.swing.JComboBox<String> jComboBox_Se4;
    private javax.swing.JComboBox<String> jComboBox_Special;
    private javax.swing.JComboBox<String> jComboBox_Tag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
